### PR TITLE
Fix up legacy branch.

### PR DESCRIPTION
**Pull request by zenspider**
1) Fix Rakefile to subclass parsers w/ RubyParser::LegacyParser.
2) Remove NEW_VERSIONS. It shouldn't be needed in the long run.
3) Fix up parser instantiation to use legacy lexer.

### CODE REVIEW

**Comment by presidentbeef** [comment]
I think we still need the `NEW_VERSIONS` dance, otherwise this happens:

```
2.3.0 :001 > require 'ruby_parser/legacy'
 => true 
2.3.0 :002 > RubyParser::VERSIONS
 => [RubyParser::V19, RubyParser::V18] 
```

**Comment by zenspider** [comment]
That is intentional.

I think indicative of where I thought we were not seeing eye to eye yesterday.

# In My Mind:

1. The legacy gem is going to depend on ruby_parser.
2. The legacy gem will do/have as little as possible to exist and keep the 1.8 and 1.9 parsers alive.
3. Those legacy parsers will hook into `RubyParser::VERSIONS`
4. As long as they can instantiate and have a `process` method that returns a Sexp, it should Just Work™. (there might be other contractual obligations I'm forgetting, but that's the gist).

**Comment by presidentbeef** [comment]
I don't understand how any of those four points (none of which I think I disagree with) relates to me wanting this:

```
2.3.0 :001 > require "ruby_parser/legacy"
 => true 
2.3.0 :002 > RubyParser::VERSIONS
 => [RubyParser::V25, RubyParser::V24, RubyParser::V23, RubyParser::V22, RubyParser::V21, RubyParser::V20, RubyParser::V19, RubyParser::V18] 
```

Which I can get just by having this:

```diff
+module RubyParserLegacy
+  NEW_VERSIONS = ::RubyParser::VERSIONS.dup
+end
+
 require "ruby_parser/legacy/ruby18_parser"
 require "ruby_parser/legacy/ruby19_parser"
 
 class RubyParser
   VERSIONS.clear
+  VERSIONS.concat RubyParserLegacy::NEW_VERSIONS
+
   class V19 < Ruby19Parser; end
   class V18 < Ruby18Parser; end
 end
```

All those parsers are being loaded anyway, right? This array is just for the fallback mechanism, which I'd like to have continue working as it does now.

**Comment by zenspider** [comment]
5. In the end you'll just do this:

```
require "ruby_parser"
require "ruby_parser/legacy"
p RubyParser::VERSIONS
# => [RubyParser::V25, RubyParser::V24, RubyParser::V23, RubyParser::V22, RubyParser::V21, RubyParser::V20, RubyParser::V19, RubyParser::V18]
```

**Comment by presidentbeef** [comment]
Is that the behavior you are getting currently with this branch?

I'm not able to replicate.

I'm also not sure what requiring `ruby_parser` first would change, since it is loaded in `legacy.rb` already. So I'm confused.

**Comment by presidentbeef** [comment]
@zenspider is there a change you are planning to make in ruby_parser for this to work?

**Comment by zenspider** [comment]
This is done, yes?

**Comment by presidentbeef** [comment]
Yep :+1:

**Pull request closed without merging**
